"""crear tablas fichas y codigos_qr

Revision ID: 0118b2a09de3
Revises: ed4cd4d997ab
Create Date: 2026-07-18 05:33:33.429802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0118b2a09de3'
down_revision: Union[str, Sequence[str], None] = 'ed4cd4d997ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('radio_metros', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sedes_id'), 'sedes', ['id'], unique=False)
    op.create_table('fichas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('numero_ficha', sa.Integer(), nullable=False),
    sa.Column('nombre_programa', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_ficha')
    )
    op.create_index(op.f('ix_fichas_id'), 'fichas', ['id'], unique=False)
    op.create_index(op.f('ix_fichas_instructor_id'), 'fichas', ['instructor_id'], unique=False)
    op.create_table('codigos_qr',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('expiracion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codigos_qr_ficha_id'), 'codigos_qr', ['ficha_id'], unique=False)
    op.create_index(op.f('ix_codigos_qr_id'), 'codigos_qr', ['id'], unique=False)
    op.create_index(op.f('ix_codigos_qr_instructor_id'), 'codigos_qr', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_codigos_qr_sede_id'), 'codigos_qr', ['sede_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codigos_qr_sede_id'), table_name='codigos_qr')
    op.drop_index(op.f('ix_codigos_qr_instructor_id'), table_name='codigos_qr')
    op.drop_index(op.f('ix_codigos_qr_id'), table_name='codigos_qr')
    op.drop_index(op.f('ix_codigos_qr_ficha_id'), table_name='codigos_qr')
    op.drop_table('codigos_qr')
    op.drop_index(op.f('ix_fichas_instructor_id'), table_name='fichas')
    op.drop_index(op.f('ix_fichas_id'), table_name='fichas')
    op.drop_table('fichas')
    op.drop_index(op.f('ix_sedes_id'), table_name='sedes')
    op.drop_table('sedes')
    # ### end Alembic commands ###
