"""crear tabla asistencias

Revision ID: 15acd655047e
Revises: 0118b2a09de3
Create Date: 2026-07-31 04:38:09.867056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15acd655047e'
down_revision: Union[str, Sequence[str], None] = '0118b2a09de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aprendiz_id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('codigo_id', sa.String(), nullable=False),
    sa.Column('creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aprendiz_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['codigo_id'], ['codigos_qr.id'], ),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencias_aprendiz_id'), 'asistencias', ['aprendiz_id'], unique=False)
    op.create_index(op.f('ix_asistencias_codigo_id'), 'asistencias', ['codigo_id'], unique=False)
    op.create_index(op.f('ix_asistencias_ficha_id'), 'asistencias', ['ficha_id'], unique=False)
    op.create_index(op.f('ix_asistencias_id'), 'asistencias', ['id'], unique=False)
    op.create_index(op.f('ix_asistencias_sede_id'), 'asistencias', ['sede_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asistencias_sede_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_ficha_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_codigo_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_aprendiz_id'), table_name='asistencias')
    op.drop_table('asistencias')
    # ### end Alembic commands ###
