"""add tipo and es_tarde to asistencias

Revision ID: a895418ca6d0
Revises: e3b07f5ed3e2
Create Date: 2026-09-24 03:12:18.545335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a895418ca6d0'
down_revision: Union[str, Sequence[str], None] = 'e3b07f5ed3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Agregar columnas como nullable primero
    op.add_column('asistencias', sa.Column('tipo', sa.String(), nullable=True))
    op.add_column('asistencias', sa.Column('es_tarde', sa.Boolean(), nullable=True))
    
    # 2. Actualizar registros existentes con valores por defecto
    op.execute("UPDATE asistencias SET tipo = 'qr' WHERE tipo IS NULL")
    op.execute("UPDATE asistencias SET es_tarde = FALSE WHERE es_tarde IS NULL")
    
    # 3. Hacer las columnas NOT NULL con valores por defecto
    op.alter_column('asistencias', 'tipo',
               existing_type=sa.String(),
               nullable=False,
               server_default='qr')
    op.alter_column('asistencias', 'es_tarde',
               existing_type=sa.Boolean(),
               nullable=False,
               server_default='false')
    
    # 4. Hacer codigo_id nullable (si es necesario)
    op.alter_column('asistencias', 'codigo_id',
               existing_type=sa.VARCHAR(),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asistencias', type_='foreignkey')
    op.create_foreign_key(op.f('asistencias_codigo_id_fkey'), 'asistencias', 'codigos_qr', ['codigo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('asistencias', 'es_tarde')
    op.drop_column('asistencias', 'tipo')
    # ### end Alembic commands ###
