"""agregar salones, franjas_clase, trimestres, horarios; quitar instructor_id de fichas; agregar ficha_id a usuarios

Revision ID: e3b07f5ed3e2
Revises: 15acd655047e
Create Date: 2026-08-12 03:58:20.664243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b07f5ed3e2'
down_revision: Union[str, Sequence[str], None] = '15acd655047e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('franjas_clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('jornada', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_franjas_clase_id'), 'franjas_clase', ['id'], unique=False)
    op.create_table('trimestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_trimestres_id'), 'trimestres', ['id'], unique=False)
    op.create_table('salones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salones_id'), 'salones', ['id'], unique=False)
    op.create_index(op.f('ix_salones_sede_id'), 'salones', ['sede_id'], unique=False)
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('franja_id', sa.Integer(), nullable=False),
    sa.Column('trimestre_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(), nullable=False),
    sa.Column('tematica', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas.id'], ),
    sa.ForeignKeyConstraint(['franja_id'], ['franjas_clase.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salones.id'], ),
    sa.ForeignKeyConstraint(['trimestre_id'], ['trimestres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horarios_ficha_id'), 'horarios', ['ficha_id'], unique=False)
    op.create_index(op.f('ix_horarios_franja_id'), 'horarios', ['franja_id'], unique=False)
    op.create_index(op.f('ix_horarios_id'), 'horarios', ['id'], unique=False)
    op.create_index(op.f('ix_horarios_instructor_id'), 'horarios', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_horarios_salon_id'), 'horarios', ['salon_id'], unique=False)
    op.create_index(op.f('ix_horarios_trimestre_id'), 'horarios', ['trimestre_id'], unique=False)
    op.add_column('codigos_qr', sa.Column('horario_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_codigos_qr_horario_id'), 'codigos_qr', ['horario_id'], unique=False)
    op.create_foreign_key(None, 'codigos_qr', 'horarios', ['horario_id'], ['id'])
    op.drop_index(op.f('ix_fichas_instructor_id'), table_name='fichas')
    op.drop_constraint(op.f('fichas_instructor_id_fkey'), 'fichas', type_='foreignkey')
    op.drop_column('fichas', 'instructor_id')
    op.add_column('usuarios', sa.Column('ficha_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_usuarios_ficha_id'), 'usuarios', ['ficha_id'], unique=False)
    op.create_foreign_key(None, 'usuarios', 'fichas', ['ficha_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_index(op.f('ix_usuarios_ficha_id'), table_name='usuarios')
    op.drop_column('usuarios', 'ficha_id')
    op.add_column('fichas', sa.Column('instructor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fichas_instructor_id_fkey'), 'fichas', 'usuarios', ['instructor_id'], ['id'])
    op.create_index(op.f('ix_fichas_instructor_id'), 'fichas', ['instructor_id'], unique=False)
    op.drop_constraint(None, 'codigos_qr', type_='foreignkey')
    op.drop_index(op.f('ix_codigos_qr_horario_id'), table_name='codigos_qr')
    op.drop_column('codigos_qr', 'horario_id')
    op.drop_index(op.f('ix_horarios_trimestre_id'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_salon_id'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_instructor_id'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_id'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_franja_id'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_ficha_id'), table_name='horarios')
    op.drop_table('horarios')
    op.drop_index(op.f('ix_salones_sede_id'), table_name='salones')
    op.drop_index(op.f('ix_salones_id'), table_name='salones')
    op.drop_table('salones')
    op.drop_index(op.f('ix_trimestres_id'), table_name='trimestres')
    op.drop_table('trimestres')
    op.drop_index(op.f('ix_franjas_clase_id'), table_name='franjas_clase')
    op.drop_table('franjas_clase')
    # ### end Alembic commands ###
